# Generated by Django 4.2.6 on 2023-10-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="outfit_images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="outfit_images/")),
            ],
        ),
        migrations.CreateModel(
            name="outfits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("gender", models.CharField(max_length=6)),
                ("mobile_no", models.BigIntegerField()),
                ("occasion", models.CharField(max_length=20)),
            ],
        ),
    ]
