# Generated by Django 4.2.6 on 2023-11-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="outfit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("mobile_no", models.BigIntegerField()),
                ("email", models.CharField(max_length=30)),
                ("User_Id", models.CharField(max_length=30)),
                ("Password", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="outfit_image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("User_Id", models.CharField(max_length=25)),
                ("Top", models.ImageField(null=True, upload_to="outfit_images/")),
                ("Bottom", models.ImageField(null=True, upload_to="outfit_images/")),
                ("Dress", models.ImageField(null=True, upload_to="outfit_images/")),
                ("Shoes", models.ImageField(upload_to="outfit_images/")),
                ("Outerwear", models.ImageField(upload_to="outfit_images/")),
                ("Purse", models.ImageField(upload_to="outfit_images/")),
                ("Compatibility_Score", models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="outfit_images",
        ),
        migrations.DeleteModel(
            name="outfits",
        ),
    ]
