# Generated by Django 4.2.6 on 2023-11-23 17:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recommendation", "0004_alter_outfit_image_compatibility_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="outfit",
            name="User_Id",
        ),
    ]
