# Generated by Django 4.2.6 on 2023-11-23 20:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recommendation", "0007_alter_outfit_image_outerwear_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="outfit",
            name="User_Id",
        ),
    ]
