# Generated by Django 4.2.6 on 2023-11-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendation", "0002_outfit_outfit_image_delete_outfit_images_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="credentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("Password", models.CharField(max_length=50)),
            ],
        ),
    ]
