# Generated by Django 4.2.6 on 2023-11-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendation", "0003_credentials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outfit_image",
            name="Compatibility_Score",
            field=models.FloatField(null=True),
        ),
    ]
