# Generated by Django 4.2.6 on 2023-11-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendation", "0005_remove_outfit_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="outfit",
            name="User_Id",
            field=models.CharField(default="please", max_length=30),
        ),
    ]
