# Generated by Django 4.2.6 on 2023-11-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendation", "0006_outfit_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outfit_image",
            name="Outerwear",
            field=models.ImageField(null=True, upload_to="outfit_images/"),
        ),
        migrations.AlterField(
            model_name="outfit_image",
            name="Purse",
            field=models.ImageField(null=True, upload_to="outfit_images/"),
        ),
    ]
