# Generated by Django 4.2.6 on 2023-11-24 06:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recommendation", "0008_remove_outfit_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="outfit_image",
            old_name="User_Id",
            new_name="User_Name",
        ),
    ]
